#!/usr/bin/env bash
# gen_codepages.sh — regenerate src/core/codepages.zig and the iconv MFIC oracle
# fixture (src/core/fixtures/codepages_iconv_oracle.tsv).
#
# Strategy (see the MFIC discipline in CLAUDE.md):
#   - TABLE VALUES are written mechanically from the authoritative Unicode
#     Consortium MAPPINGS text files (VISCII has no unicode.org file, so it comes
#     from perl's Encode, an independent decoder). This is "write the mappings
#     yourself", not a runtime dependency — the result is baked into pure Zig so
#     the wasm32-freestanding slice keeps working with zero imports.
#   - The ORACLE is GNU/Apple `iconv` (Peter's call). Every table is checked
#     against iconv over all 256 bytes by encoding_test (via the emitted fixture).
#   Generator (MAPPINGS/perl) != checker (iconv): maker-ne-checker independence.
#
# Requires: network (to fetch MAPPINGS), iconv, perl (with Encode), luajit|lua, awk.
# Run from the repo root:  ./tools/gen_codepages.sh
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_ZIG="$ROOT/src/core/codepages.zig"
OUT_ORACLE="$ROOT/src/core/fixtures/codepages_iconv_oracle.tsv"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

BASE="https://www.unicode.org/Public/MAPPINGS"

# charset -> MAPPINGS url (single-byte charsets chardetz.detect can identify,
# minus CJK multibyte which is out of scope, minus WINDOWS-1252/ISO-8859-1/
# MAC-ROMAN/ASCII/UTF-8 which encoding.zig already handles directly).
declare -A URL=(
	[ISO-8859-2]="$BASE/ISO8859/8859-2.TXT"
	[ISO-8859-3]="$BASE/ISO8859/8859-3.TXT"
	[ISO-8859-5]="$BASE/ISO8859/8859-5.TXT"
	[ISO-8859-6]="$BASE/ISO8859/8859-6.TXT"
	[ISO-8859-7]="$BASE/ISO8859/8859-7.TXT"
	[ISO-8859-8]="$BASE/ISO8859/8859-8.TXT"
	[ISO-8859-9]="$BASE/ISO8859/8859-9.TXT"
	[ISO-8859-11]="$BASE/ISO8859/8859-11.TXT"
	[ISO-8859-15]="$BASE/ISO8859/8859-15.TXT"
	[WINDOWS-1250]="$BASE/VENDORS/MICSFT/WINDOWS/CP1250.TXT"
	[WINDOWS-1251]="$BASE/VENDORS/MICSFT/WINDOWS/CP1251.TXT"
	[WINDOWS-1253]="$BASE/VENDORS/MICSFT/WINDOWS/CP1253.TXT"
	[WINDOWS-1255]="$BASE/VENDORS/MICSFT/WINDOWS/CP1255.TXT"
	[WINDOWS-1256]="$BASE/VENDORS/MICSFT/WINDOWS/CP1256.TXT"
	[WINDOWS-1258]="$BASE/VENDORS/MICSFT/WINDOWS/CP1258.TXT"
	[KOI8-R]="$BASE/VENDORS/MISC/KOI8-R.TXT"
	[IBM855]="$BASE/VENDORS/MICSFT/PC/CP855.TXT"
	[IBM866]="$BASE/VENDORS/MICSFT/PC/CP866.TXT"
)
# Order tables appear in codepages.zig (VISCII appended after the MAPPINGS set).
ORDER=(ISO-8859-2 ISO-8859-3 ISO-8859-5 ISO-8859-6 ISO-8859-7 ISO-8859-8 ISO-8859-9 ISO-8859-11 ISO-8859-15 WINDOWS-1250 WINDOWS-1251 WINDOWS-1253 WINDOWS-1255 WINDOWS-1256 WINDOWS-1258 KOI8-R IBM855 IBM866)

echo ">> downloading Unicode MAPPINGS files"
for cs in "${ORDER[@]}"; do
	curl -fsS --max-time 30 -o "$WORK/$cs.TXT" "${URL[$cs]}" || { echo "FAIL download $cs"; exit 1; }
done

echo ">> building table.tsv (CHARSET<TAB>BYTE<TAB>CODEPOINT) from MAPPINGS + perl(VISCII)"
: > "$WORK/table.tsv"
for cs in "${ORDER[@]}"; do
	awk -v CS="$cs" '
		BEGIN { for (i=0;i<256;i++) cp[i]="FFFD" }
		/^[[:space:]]*#/ { next }
		{ if (match($0,/^0[xX]([0-9A-Fa-f]+)[[:space:]]+0[xX]([0-9A-Fa-f]+)/,m)) { b=strtonum("0x"m[1]); u=strtonum("0x"m[2]); if (b<=255) cp[b]=sprintf("%04X",u) } }
		END { for (i=0;i<256;i++) printf "%s\t%02X\t%s\n", CS, i, cp[i] }
	' "$WORK/$cs.TXT" >> "$WORK/table.tsv"
done
# VISCII from perl Encode (no unicode.org MAPPINGS file exists for it).
perl -MEncode -e '
	for my $b (0..255) {
		my $u = eval { Encode::decode("viscii", chr($b), Encode::FB_CROAK) };
		if (defined $u && length($u)==1) { printf "VISCII\t%02X\t%04X\n", $b, ord($u); }
		else { printf "VISCII\t%02X\tFFFD\n", $b; }
	}' >> "$WORK/table.tsv"

echo ">> emitting $OUT_ZIG"
cat > "$WORK/emit.lua" <<'LUA'
local infile, outfile = arg[1], arg[2]
local order, tbl = {}, {}
for line in io.lines(infile) do
	local cs, hb, hc = line:match("^(%S+)\t(%x%x)\t(%x+)$")
	if cs then
		if not tbl[cs] then tbl[cs] = {}; order[#order+1] = cs end
		tbl[cs][tonumber(hb,16)] = tonumber(hc,16)
	end
end
local function slug(cs) return (cs:lower():gsub("[%-]","_")) end
local out = {}
local function w(s) out[#out+1] = s end
w("//! @generated by tools/gen_codepages.sh — DO NOT EDIT BY HAND.")
w("//!")
w("//! Single-byte legacy codepage → Unicode conversion tables, one [256]u21")
w("//! per charset (0xFFFD marks a byte that is undefined in the source charset).")
w("//! These let docscan transcode any single-byte encoding chardetz.detect() can")
w("//! identify — Cyrillic, Greek, Hebrew, Arabic, Thai, Turkish, Vietnamese,")
w("//! Central-European, etc. — to UTF-8, in pure Zig with no runtime dependency")
w("//! (so the wasm32-freestanding slice keeps working). CJK multibyte is out of")
w("//! scope for now (handled by chardetz detection but not yet transcoded here).")
w("//!")
w("//! ORACLE: GNU/Apple `iconv` is the source of truth (Peter's call). The table")
w("//! values are written mechanically from the Unicode Consortium MAPPINGS files")
w("//! (VISCII from perl's Encode, which has no unicode.org MAPPINGS file), and")
w("//! every table is differential-tested against `iconv` over all 256 bytes in")
w("//! codepages_test.zig. At generation time iconv and the MAPPINGS files agreed")
w("//! on all 4864 cells (0 divergences) — two independent authorities.")
w("//!")
w("//! Regenerate: `./tools/gen_codepages.sh` (needs network for MAPPINGS + iconv).")
w("")
w("/// Sentinel for a byte with no defined mapping in its source charset.")
w("pub const UNDEFINED: u21 = 0xFFFD;")
w("")
for _, cs in ipairs(order) do
	w(string.format("/// %s → Unicode (256 entries).", cs))
	w(string.format("pub const %s: [256]u21 = .{", slug(cs)))
	for row = 0, 15 do
		local parts = {}
		for col = 0, 15 do
			local b = row*16+col
			parts[#parts+1] = string.format("0x%04X", tbl[cs][b] or 0xFFFD)
		end
		w(string.format("\t%s, // %02X-%02X", table.concat(parts, ", "), row*16, row*16+15))
	end
	w("};")
	w("")
end
w("/// Map a charset name as emitted by chardetz.detect() (or a PDF /Encoding) to")
w("/// its single-byte conversion table, or null if it is not a single-byte")
w("/// codepage handled here (UTF-8/ASCII/UTF-16/32 and CJK go through other paths).")
w("pub fn tableFor(name: []const u8) ?*const [256]u21 {")
w("\tconst eql = @import(\"std\").mem.eql;")
for _, cs in ipairs(order) do
	w(string.format("\tif (eql(u8, name, \"%s\")) return &%s;", cs, slug(cs)))
end
w("\t// TIS-620 (Thai) is byte-identical to ISO-8859-11.")
w("\tif (eql(u8, name, \"TIS-620\")) return &iso_8859_11;")
w("\treturn null;")
w("}")
w("")
local fh = assert(io.open(outfile, "w"))
fh:write(table.concat(out, "\n"))
fh:close()
LUA
(luajit "$WORK/emit.lua" "$WORK/table.tsv" "$OUT_ZIG" 2>/dev/null) || lua "$WORK/emit.lua" "$WORK/table.tsv" "$OUT_ZIG"

echo ">> emitting $OUT_ORACLE (iconv, the independent oracle)"
# name|iconv-name pairs: the codepages.zig set + TIS-620 alias + the two
# encoding.zig-owned tables iconv agrees with cleanly (WINDOWS-1252/ISO-8859-1).
# MAC-ROMAN is intentionally OMITTED: Apple's iconv "MACINTOSH" diverges from the
# canonical Unicode VENDORS/APPLE/ROMAN.TXT on control/PUA bytes (e.g. it refuses
# 0x7F DEL and the Apple-logo PUA), so it is a poor oracle for MacRoman. MacRoman
# is covered by encoding.zig's own dedicated unit tests and is not a charset
# chardetz.detect() ever returns, so it does not need the iconv differential.
PAIRS="ISO-8859-2|ISO-8859-2 ISO-8859-3|ISO-8859-3 ISO-8859-5|ISO-8859-5 ISO-8859-6|ISO-8859-6 ISO-8859-7|ISO-8859-7 ISO-8859-8|ISO-8859-8 ISO-8859-9|ISO-8859-9 ISO-8859-11|ISO-8859-11 ISO-8859-15|ISO-8859-15 WINDOWS-1250|WINDOWS-1250 WINDOWS-1251|WINDOWS-1251 WINDOWS-1253|WINDOWS-1253 WINDOWS-1255|WINDOWS-1255 WINDOWS-1256|WINDOWS-1256 WINDOWS-1258|WINDOWS-1258 KOI8-R|KOI8-R IBM855|IBM855 IBM866|IBM866 VISCII|VISCII TIS-620|TIS-620 WINDOWS-1252|WINDOWS-1252 ISO-8859-1|ISO-8859-1"
{
	echo "# @generated by tools/gen_codepages.sh — DO NOT EDIT BY HAND."
	echo "# Independent MFIC oracle for src/core/codepages.zig + encoding.zig toUtf8 tables."
	echo "# Source: GNU/Apple iconv (-f CHARSET -t UTF-32BE), all 256 bytes per charset."
	echo "# Columns: CHARSET<TAB>BYTE(hex)<TAB>CODEPOINT(hex, FFFD = undefined/invalid)."
	echo "# The codepages.zig tables are written from Unicode MAPPINGS (VISCII via perl"
	echo "# Encode); this file is iconv's independent view. encoding_test asserts they"
	echo "# agree per byte. iconv vs MAPPINGS agreed on all cells at generation (0 div)."
	for pair in $PAIRS; do
		name="${pair%%|*}"; icn="${pair##*|}"
		for b in $(seq 0 255); do
			hexb=$(printf '%02X' "$b")
			cp=$(printf "\\x$hexb" | iconv -f "$icn" -t UTF-32BE 2>/dev/null | od -An -tx1 | tr -d ' \n')
			if [ -n "$cp" ] && [ ${#cp} -eq 8 ]; then printf '%s\t%s\t%s\n' "$name" "$hexb" "$(printf '%04X' "0x$cp")"; else printf '%s\t%s\tFFFD\n' "$name" "$hexb"; fi
		done
	done
} > "$OUT_ORACLE"

echo ">> done. Tables: $(grep -c '^pub const .*: \[256\]u21' "$OUT_ZIG")  Oracle rows: $(grep -vc '^#' "$OUT_ORACLE")"
